### ISSUE TITLE
Ukranian translation throws errors in a newly created adapter (adapter-react)

### ISSUE THREAD

**Issue by Arcticon** [AlCalzone/create-adapter#1105]
https://github.com/ioBroker/create-adapter/blame/90a27e606bc9501f3798fc0f02fcc175e1623e86/templates/admin/src/app.tsx_jsx.ts#L44

See: #1001 

Error:
```
GenericApp.js:119 Uncaught TypeError: Cannot convert undefined or null to object
    at Function.assign (<anonymous>)
    at GenericApp.js:119:92
    at Array.forEach (<anonymous>)
    at new GenericApp3 (GenericApp.js:119:48)
    at new App (app.tsx:32:9)
    at constructClassInstance (react-dom.development.js:12716:18)
    at updateClassComponent (react-dom.development.js:17425:5)
    at beginWork (react-dom.development.js:19073:16)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:3945:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:16)
```

this is because the current create-adapter code installs adapter-react, which in fact does not support the ukranian translation: https://github.com/ioBroker/adapter-react/blob/master/src/GenericApp.js#L106
this could be fixed with a switch to adapter-react-v5: #1096

**Comment by Arcticon** [comment]
See: #1095

**Comment by Arcticon** [comment]
Possible solutions:
* Drop ukranian translation (until adapter v5 is fully supported) in favor of a fully working adapter
* Fully support the ukranian translation in adapter-react in favor of a fully working adapter
* Finish adapter v5 support: #1096 

1 and 2 are done in 1min, but i prefer number 2.

**Comment by Apollon77** [comment]
duplicate #1095
