### ISSUE TITLE
Allow to choose for dev-server if local or global dep

### ISSUE THREAD

**Issue by Apollon77** [AlCalzone/create-adapter#864]
The current "Do you want to use dev-server" question should get three options:
* as local devDep ... and add it to the package.json and add all relevant "Ignore files and such"
* as global Depenednency (with warning that it might require additional acces to be installed (and catch error if an error happens on global install)
* No

maybe also bring this question more to the from to the other tools becazse eslint, prettier and devcontainer are asked at the very beginning ... I also wondered if dev-server would come at all

**Comment by derAlff** [comment]
I have a problem... If I clone the "create-adapter" from github and run it with `npx @iobroker/create-adapter`, then I have the following issue by installing the dev-server

```
[3/3] Installing dev-server...
npm ERR! code EACCES
npm ERR! syscall access
npm ERR! path /usr/lib/node_modules
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, access '/usr/lib/node_modules'
npm ERR!  [Error: EACCES: permission denied, access '/usr/lib/node_modules'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/lib/node_modules'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/oliver/.npm/_logs/2022-03-03T18_14_56_852Z-debug.log
```


After changing the permissions (set permissions of the foder to my user and also this group), there is a new issue by install the dev-server


```
npm ERR! code EACCES
npm ERR! syscall symlink
npm ERR! path ../lib/node_modules/@iobroker/dev-server/dist/index.js
npm ERR! dest /usr/bin/iobroker-dev-server
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, symlink '../lib/node_modules/@iobroker/dev-server/dist/index.js' -> '/usr/bin/iobroker-dev-server'
npm ERR!  [OperationalError: EACCES: permission denied, symlink '../lib/node_modules/@iobroker/dev-server/dist/index.js' -> '/usr/bin/iobroker-dev-server'] {
npm ERR!   cause: [Error: EACCES: permission denied, symlink '../lib/node_modules/@iobroker/dev-server/dist/index.js' -> '/usr/bin/iobroker-dev-server'] {
npm ERR!     errno: -13,
npm ERR!     code: 'EACCES',
npm ERR!     syscall: 'symlink',
npm ERR!     path: '../lib/node_modules/@iobroker/dev-server/dist/index.js',
npm ERR!     dest: '/usr/bin/iobroker-dev-server'
npm ERR!   },
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'symlink',
npm ERR!   path: '../lib/node_modules/@iobroker/dev-server/dist/index.js',
npm ERR!   dest: '/usr/bin/iobroker-dev-server'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/oliver/.npm/_logs/2022-03-03T18_19_08_554Z-debug.log
events.js:377
      throw er; // Unhandled 'error' event
      ^

Error: spawn iobroker-dev-server ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:280:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn iobroker-dev-server',
  path: 'iobroker-dev-server',
  spawnargs: [ 'setup', '--adminPort', '8081' ]
}
```

If i cange the permissions of this folder too, it runs... but i don't kow... can i let it so?
Running developing under Linux Mint
