### ISSUE TITLE
npx @iobroker/create-adapter not working

### ISSUE THREAD

**Issue by Eistee82** [AlCalzone/create-adapter#882]
Hi I have a proxmox LXC debian container and cann't run the create-adapter
Someone can tell me why?

`root@iobroker:/opt/iobroker# root@iobroker:/opt/iobroker# npx @iobroker/create-adapter
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module '/root/.npm/_npx/28875/lib/node_modules/@iobroker/create-adapter/node_modules/esbuild/install.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! esbuild@0.14.23 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the esbuild@0.14.23 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-02-28T18_08_39_783Z-debug.log
Install for [ '@iobroker/create-adapter@latest' ] failed with code 1
`

**Comment by AlCalzone** [comment]
This looks like you're trying to use it in a production environment (/opt/iobroker). You're not supposed to do that. I wouldn't be surprised if there is some kind of dependency conflict.

If you want to test with a "real" iobroker instance, generate an adapter on your dev system and use https://github.com/ioBroker/dev-server in the generated directory.

**Comment by derAlff** [comment]
I have the same problem... If I clone the "create-adapter" from github and run it with `npx @iobroker/create-adapter`, then I have the following issue by installing the dev-server

```
[3/3] Installing dev-server...
npm ERR! code EACCES
npm ERR! syscall access
npm ERR! path /usr/lib/node_modules
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, access '/usr/lib/node_modules'
npm ERR!  [Error: EACCES: permission denied, access '/usr/lib/node_modules'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/lib/node_modules'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/oliver/.npm/_logs/2022-03-03T18_14_56_852Z-debug.log
```


After changing the permissions (set permissions of the foder to my user and also this group), there is a new issue by install the dev-server


```
npm ERR! code EACCES
npm ERR! syscall symlink
npm ERR! path ../lib/node_modules/@iobroker/dev-server/dist/index.js
npm ERR! dest /usr/bin/iobroker-dev-server
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, symlink '../lib/node_modules/@iobroker/dev-server/dist/index.js' -> '/usr/bin/iobroker-dev-server'
npm ERR!  [OperationalError: EACCES: permission denied, symlink '../lib/node_modules/@iobroker/dev-server/dist/index.js' -> '/usr/bin/iobroker-dev-server'] {
npm ERR!   cause: [Error: EACCES: permission denied, symlink '../lib/node_modules/@iobroker/dev-server/dist/index.js' -> '/usr/bin/iobroker-dev-server'] {
npm ERR!     errno: -13,
npm ERR!     code: 'EACCES',
npm ERR!     syscall: 'symlink',
npm ERR!     path: '../lib/node_modules/@iobroker/dev-server/dist/index.js',
npm ERR!     dest: '/usr/bin/iobroker-dev-server'
npm ERR!   },
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'symlink',
npm ERR!   path: '../lib/node_modules/@iobroker/dev-server/dist/index.js',
npm ERR!   dest: '/usr/bin/iobroker-dev-server'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/oliver/.npm/_logs/2022-03-03T18_19_08_554Z-debug.log
events.js:377
      throw er; // Unhandled 'error' event
      ^

Error: spawn iobroker-dev-server ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:280:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn iobroker-dev-server',
  path: 'iobroker-dev-server',
  spawnargs: [ 'setup', '--adminPort', '8081' ]
}
```

If i cange the permissions of this folder too, it runs... but i don't kow... can i let it so?

PS: Running developing under Linux Mint

**Comment by AlCalzone** [comment]
@UncleSamSwiss I think we may have a permission problem with the global dev-server installation. @Apollon77 mentioned something similar

**Comment by UncleSamSwiss** [comment]
@necotec , sorry, but your problem is not at all related to the OP.

@AlCalzone, yes, apparently there is no "per-user" global installation in npm on *nix systems, so this will only work with sudo or as a dev-dependency (or by running dev-server with npx) - see also #864

**Comment by derAlff** [comment]
@UncleSamSwiss Ok, is it ok when i create a new issue?

**Comment by UncleSamSwiss** [comment]
> Ok, is it ok when i create a new issue?

Just add a comment on #864

**Comment by AlCalzone** [comment]
> If I clone the "create-adapter" from github and run it with `npx @iobroker/create-adapter`

@necotec Are you really cloning the repo from github? And if yes, why? The [usage guide](https://github.com/ioBroker/create-adapter#usage) doesn't mention cloning.

**Comment by derAlff** [comment]
hmm....
yep, i clone the complete repo

**Comment by AlCalzone** [comment]
Yeah, that's not necessary.

**Comment by derAlff** [comment]
@AlCalzone One moment... i test ist...

**Comment by derAlff** [comment]
@AlCalzone when i only use the command, then i can not start the dev-server (Permissions to the folders reset to `root`)

**Comment by AlCalzone** [comment]
Yeah, that's a different problem we need to solve. You can install dev-server manually with
```
sudo npm i -g @iobroker/dev-server
```
and create the adapter without dev-server.

**Comment by derAlff** [comment]
Uuuuuh, now I have some other problems...

**Comment by derAlff** [comment]
@AlCalzone same problem when i have `root` as owner of `/usr/bin/` and `/usr/lib/node_modules`

Here the message in my terminal (and i use the cloned repo in the future ;) )

```
oliver@PC-BUERO:~/git/create-adapter/ioBroker.a$ dev-server watch default
Using profile name "default"
Using adapter name "a"
Install local iobroker.a
/home/oliver/git/create-adapter/ioBroker.a> npm pack
Packed to iobroker.a-0.0.1.tgz
/home/oliver/git/create-adapter/ioBroker.a/.dev-server/default> npm install "/home/oliver/git/create-adapter/ioBroker.a/iobroker.a-0.0.1.tgz"
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ iobroker.a@0.0.1
updated 1 package and audited 394 packages in 3.488s

18 packages are looking for funding
  run `npm fund` for details

found 5 vulnerabilities (3 low, 1 moderate, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details
/home/oliver/git/create-adapter/ioBroker.a/.dev-server/default> node node_modules/iobroker.js-controller/controller.js
Running inside /home/oliver/git/create-adapter/ioBroker.a/.dev-server/default
Starting browser-sync
[HPM] Proxy created: /adapter/a/**,/browser-sync/**  -> http://localhost:22426
[HPM] Proxy rewrite rule created: "^/adapter/a/" ~> "/"
[HPM] Proxy created: !/adapter/a/**,!/browser-sync/**  -> http://localhost:20426
Starting web server on port 8081
╭─────────────────────────────────────────────────────────╮
│                                                         │
│   Admin is now reachable under http://localhost:8081/   │
│                                                         │
╰─────────────────────────────────────────────────────────╯
WebSocket error: Error: connect ECONNREFUSED 127.0.0.1:20426
WebSocket closed
Starting file system sync from /home/oliver/git/create-adapter/ioBroker.a
Synchronizing main.js
Starting nodemon for /home/oliver/git/create-adapter/ioBroker.a/.dev-server/default/node_modules/iobroker.a/main.js
Created /home/oliver/git/create-adapter/ioBroker.a/.dev-server/default/node_modules/iobroker.a/main.js.map from /home/oliver/git/create-adapter/ioBroker.a/main.js
[nodemon] 2.0.15
[nodemon] to restart at any time, enter `rs`
[nodemon] ignoring: ./.dev-server/default/node_modules/iobroker.a/admin/**/*
[nodemon] watching path(s): .dev-server/default/node_modules/iobroker.a/**/*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node --inspect /home/oliver/git/create-adapter/ioBroker.a/.dev-server/default/node_modules/iobroker.a/main.js --debug 0`
[nodemon] spawning
[nodemon] child pid: 59625
Debugger listening on ws://127.0.0.1:9229/7f7c2782-5e26-4239-b514-81cec536cb14
For help, see: https://nodejs.org/en/docs/inspector
[nodemon] watching 7 files
╭───────────────────────────────────────────────────╮
│                                                   │
│   Debugger is now available on process id 59626   │
│                                                   │
╰───────────────────────────────────────────────────╯
2022-03-03 21:14:50.701  - info: host.dev-a-PC-BUERO iobroker.js-controller version 4.0.15 js-controller starting
2022-03-03 21:14:50.704  - info: host.dev-a-PC-BUERO Copyright (c) 2014-2022 bluefox, 2014 hobbyquaker
2022-03-03 21:14:50.705  - info: host.dev-a-PC-BUERO hostname: dev-a-PC-BUERO, node: v14.19.0
2022-03-03 21:14:50.705  - info: host.dev-a-PC-BUERO ip addresses: 192.168.11.109 fd00::6867:9a7e:a42f:52f6 fd00::19e3:3a08:ddbc:7e81 fe80::91e9:76e:b4a9:b197
2022-03-03 21:14:50.711  - debug: host.dev-a-PC-BUERO-Server Data File: /home/oliver/git/create-adapter/ioBroker.a/.dev-server/default/iobroker-data/objects.jsonl
2022-03-03 21:14:50.797  - debug: host.dev-a-PC-BUERO-Server  Redis inMem-objects listening on port 9001
2022-03-03 21:14:50.799  - debug: host.dev-a-PC-BUERO Redis Objects: Use Redis connection: 127.0.0.1:26426
2022-03-03 21:14:50.811  - debug: host.dev-a-PC-BUERO Objects client ready ... initialize now
2022-03-03 21:14:50.813  - debug: host.dev-a-PC-BUERO Objects create System PubSub Client
2022-03-03 21:14:50.825  - debug: host.dev-a-PC-BUERO Objects client initialize lua scripts
2022-03-03 21:14:50.832  - debug: host.dev-a-PC-BUERO Objects connected to redis: 127.0.0.1:26426
2022-03-03 21:14:50.884  - debug: host.dev-a-PC-BUERO-Server Data File: /home/oliver/git/create-adapter/ioBroker.a/.dev-server/default/iobroker-data/states.jsonl
2022-03-03 21:14:50.888  - debug: host.dev-a-PC-BUERO-Server  Redis inMem-states listening on port 9000
2022-03-03 21:14:50.890  - debug: host.dev-a-PC-BUERO Redis States: Use Redis connection: 127.0.0.1:24426
2022-03-03 21:14:50.893  - debug: host.dev-a-PC-BUERO States create System PubSub Client
2022-03-03 21:14:50.897  - debug: host.dev-a-PC-BUERO States connected to redis: 127.0.0.1:24426
2022-03-03 21:14:50.915  - info: host.dev-a-PC-BUERO connected to Objects and States
2022-03-03 21:14:50.925  - info: host.dev-a-PC-BUERO added notifications configuration of host
2022-03-03 21:14:50.931  - info: host.dev-a-PC-BUERO Node.js version has changed from unknown to 14.19.0
[sudo] password for oliver: 2022-03-03 21:14:50.962  - debug: host.dev-a-PC-BUERO Plugin sentry Initialize Plugin (enabled=true)
2022-03-03 21:14:50.964  - info: host.dev-a-PC-BUERO Plugin sentry Sentry Plugin disabled for this process because sending of statistic data is disabled for the system
2022-03-03 21:14:50.995  - info: host.dev-a-PC-BUERO 2 instances found
2022-03-03 21:14:50.995  - debug: host.dev-a-PC-BUERO check instance "system.adapter.admin.0" for host "dev-a-PC-BUERO"
host.dev-a-PC-BUERO check instance "system.adapter.admin.0" for host "dev-a-PC-BUERO"
2022-03-03 21:14:50.997  - debug: host.dev-a-PC-BUERO check instance "system.adapter.a.0" for host "dev-a-PC-BUERO"
host.dev-a-PC-BUERO check instance "system.adapter.a.0" for host "dev-a-PC-BUERO"
2022-03-03 21:14:50.997  - info: host.dev-a-PC-BUERO starting 1 instance
2022-03-03 21:14:51.049  - debug: host.dev-a-PC-BUERO added notifications configuration of system.adapter.admin.0
2022-03-03 21:14:51.049  - debug: host.dev-a-PC-BUERO startInstance admin.0 loglevel=info, compact=false
2022-03-03 21:14:51.059  - info: host.dev-a-PC-BUERO instance system.adapter.admin.0 started with pid 59653
2022-03-03 21:14:51.091  - debug: a.0 (59626) Redis Objects: Use Redis connection: 127.0.0.1:26426
2022-03-03 21:14:51.109  - debug: a.0 (59626) Objects client ready ... initialize now
2022-03-03 21:14:51.110  - debug: a.0 (59626) Objects create System PubSub Client
2022-03-03 21:14:51.111  - debug: a.0 (59626) Objects create User PubSub Client
2022-03-03 21:14:51.120  - debug: a.0 (59626) Objects client initialize lua scripts
2022-03-03 21:14:51.123  - debug: a.0 (59626) Objects connected to redis: 127.0.0.1:26426
2022-03-03 21:14:51.131  - debug: a.0 (59626) Redis States: Use Redis connection: 127.0.0.1:24426
2022-03-03 21:14:51.133  - debug: a.0 (59626) States create System PubSub Client
2022-03-03 21:14:51.134  - debug: a.0 (59626) States create User PubSub Client
2022-03-03 21:14:51.138  - debug: a.0 (59626) States connected to redis: 127.0.0.1:24426
2022-03-03 21:14:51.144  - error: a.0 (59626) adapter disabled
2022-03-03 21:14:51.180  - info: a.0 (59626) starting. Version 0.0.1 in /home/oliver/git/create-adapter/ioBroker.a/.dev-server/default/node_modules/iobroker.a, node: v14.19.0, js-controller: 4.0.15
2022-03-03 21:14:51.191  - info: a.0 (59626) config option1: true
2022-03-03 21:14:51.192  - info: a.0 (59626) config option2: 42
2022-03-03 21:14:51.207  - info: a.0 (59626) state a.0.testVariable changed: true (ack = false)
2022-03-03 21:14:51.254  - info: a.0 (59626) state a.0.testVariable changed: true (ack = true)
2022-03-03 21:14:51.256  - info: a.0 (59626) state a.0.testVariable changed: true (ack = true)
WebSocket error: Error: connect ECONNREFUSED 127.0.0.1:20426
WebSocket closed
```

**Comment by UncleSamSwiss** [comment]
@necotec What's the problem now? I see the adapter properly starting and then there is a debug message about WebSockets (it's in light gray to not attract attention). Is anything not working? What happens when you navigate to http://localhost:8081/ ?

**Comment by derAlff** [comment]
@UncleSamSwiss When i have the websocket debug message, then i can not access the Admin on localhost...
It works for me, when i directly use the create-adapter projcet from github and set up the permission of the folders `/usr/bin`and `/usr/lib/node_modules` to my user. 
If I install the dev-server global, i have the  websocket issues... It's strange :( -> But for me it is ok.

If you want to see it in live, you can contact me on Telegram or Discord ;)

**Comment by AlCalzone** [comment]
The dev-server install issue is tracked separately, so I'm closing here.
